name: Deploy to GAE

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21' 
          distribution: 'adopt'
          
      - name: Set Up App
        run: |
          echo '${{ secrets.ENV }}' >> src/main/resources/application.properties
          mvn clean install -DskipTests

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v2
        with:
          deliverables: app.yaml
          project_id: ta-2-sistem-cerdas

      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}/api/hello"