name: Deploy to GAE

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Cloud Auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
      
      - name: Configure Docker Client of Gcloud
        run:  |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker asia-docker.pkg.dev --quiet

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21' 
          distribution: 'adopt'
          
      - name: Set Up App
        run: |
          echo '${{ secrets.ENV }}' >> src/main/resources/application.properties
          echo '${{ secrets.X_API_KEY }}' >> src/main/resources/application.properties
          
      - name: Set Up Image
        run: |
          mvn spring-boot:build-image -Dspring-boot.build-image.imageName=asia-docker.pkg.dev/ta-2-sistem-cerdas/asia.gcr.io/ta-2-sistem-cerdas-be
          docker push asia-docker.pkg.dev/ta-2-sistem-cerdas/asia.gcr.io/ta-2-sistem-cerdas-be

      - name: Deploy to Cloud run v2
        id: deploy-cloudrun
        run: |
          gcloud run deploy ta-2-sistem-cerdas-be \
          --image=asia-docker.pkg.dev/ta-2-sistem-cerdas/asia.gcr.io/ta-2-sistem-cerdas-be \
          --platform=managed --region=asia-southeast2 --allow-unauthenticated \
          --min-instances=1 --max-instances=1 --memory=1Gi --cpu=1 --timeout=300s